### ISSUE TITLE
./hpg-pore.sh events Fails

### ISSUE THREAD

**Issue by rtmag** [opencb/hpg-pore#3]
Hello developers,

I am quite keen on using your tools, specifically  the events program. I am using the following command: 

`./hpg-pore.sh events --in /home/rtm/nanopore/data/reads/pass/4YN3PYI_20161101_FNFAB42331_MN19395_read13_strand.fast5 --out /home/rtm/nanopore/event_out/ `

however I have the following error: 

`	at org.opencb.hpg_pore.NativePoreSupport.loadLibrary(NativePoreSupport.java:46)
	at org.opencb.hpg_pore.EventsCmd.runLocalEventsCmd(EventsCmd.java:59)
	at org.opencb.hpg_pore.EventsCmd.run(EventsCmd.java:44)
	at org.opencb.hpg_pore.Main.main(Main.java:38)
`

There were warnings during the build, but no errors. There is a raised warning regarding the event function:

`org_opencb_hpg_pore_NativePoreSupport.c: In function ‘Java_org_opencb_hpg_1pore_NativePoreSupport_getEvents’:
org_opencb_hpg_pore_NativePoreSupport.c:49:14: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  char *src = (*env)->GetStringUTFChars(env, source, 0);
`

Any idea on what is going wrong?

Thank you!
RTM

**Comment by tstrobaugh** [comment]
Similar issue, can't find a solution:

./hpg-pore.sh stats --in minion.fast5 --out out-stats

Exception in thread "main" java.lang.NullPointerException
	at org.opencb.hpg_pore.NativePoreSupport.loadLibrary(NativePoreSupport.java:46)
	at org.opencb.hpg_pore.StatsCmd.runLocalStatsCmd(StatsCmd.java:60)
	at org.opencb.hpg_pore.StatsCmd.run(StatsCmd.java:44)
	at org.opencb.hpg_pore.Main.main(Main.java:26)
